### ISSUE TITLE
Linkjes in PDF's werken niet

### ISSUE THREAD

**Issue by arjenzorgdoc** [GidsOpenStandaarden/OpenPGO#1]
Er staat blauw onderstreepte tekst in de PDF's. Dat lijkt op linkjes maar ze doen het niet.

Voorbeeld: [UCI Opvragen Whitelist.pdf](https://github.com/GidsOpenStandaarden/OpenPGO/blob/master/Resources/UCI%20Opvragen%20Whitelist.pdf) de tekst 'Applicatielaag'

(PDF is niet zo handig voor Github. Ik kan nu niet naar een bepaalde regel linken)

**Comment by relitodea** [comment]
opgelost

**Comment by arjenzorgdoc** [comment]
De linkjes doen het nog steeds niet

**Comment by relitodea** [comment]
Ik zie dat de PDF doet de linkjes eruit :  de informatie is te vinden op de publieke pagina van https://afsprakenstelsel.medmij.nl
