### ISSUE TITLE
Coding Standard: Appendix ontbreekt

### ISSUE THREAD

**Issue by arjenzorgdoc** [GidsOpenStandaarden/OpenPGO#2]
Er staat in [UCI Opvragen Whitelist.pdf](https://github.com/GidsOpenStandaarden/OpenPGO/blob/master/Resources/UCI%20Opvragen%20Whitelist.pdf)

> **Oplevering:** Coding Standard volgens Blauwdruk Design Template (zie Appendix)

Deze Appendix ontbreekt

**Comment by relitodea** [comment]
opgelost - document bijgewerkt

**Comment by arjenzorgdoc** [comment]
De appendix ontbreekt nog steeds

**Comment by relitodea** [comment]
zie Coding standards & Design.pdf  in root : https://github.com/GidsOpenStandaarden/OpenPGO/blob/master/Coding%20standards%20%20%26%20Design.pdf
