### ISSUE TITLE
UCI Opvragen Whitelist: info over deelnemende organisatie lijkt onnodig

### ISSUE THREAD

**Issue by arjenzorgdoc** [GidsOpenStandaarden/OpenPGO#3]
Er staat in UCI Opvragen Whitelist

> Als de Organisatie deelneemt als Dienstverlener zorgaanbieder is de gebruikersvriendelijke naam leeg. Als de Organisatie deelneemt als Dienstverlener persoon is de gebruikersvriendelijke naam niet leeg en gelijk aan die van de betreffende Organisatie.

Wat is de relevantie daarvan voor deze UCI?

**Comment by relitodea** [comment]
opgelost - nieuwe uplopad
