### ISSUE TITLE
UCI Opvragen Whitelist: Hoe wordt deze aangeboden?

### ISSUE THREAD

**Issue by arjenzorgdoc** [GidsOpenStandaarden/OpenPGO#4]
> **Opdracht 1**
> Definieer de API functies nodig om de Whitelist te benaderen

Hoe wordt deze aangeboden? Via een URL? Welke URL?

**Comment by relitodea** [comment]
zie document

**Comment by arjenzorgdoc** [comment]
Wat is nu de URL?

**Comment by relitodea** [comment]
Dat is een configuratie parameter - ik neem aan dat jullie gaan de file ophalen local of via een URL die te configureren  is
