### ISSUE TITLE
UCI ZA OAuth - DigiD interactie

### ISSUE THREAD

**Issue by BasKloosterman** [GidsOpenStandaarden/OpenPGO#5]
Is de DigiD interactie in de ZA OAuth opdracht deel van de opdracht?

**Comment by relitodea** [comment]
DigiD integratie is niet in de scope van deze opdracht op dit moment. Is de verantw. van de ZA Node om de DigiID integratie te ondersteunen om de toestemming van de persoon te kunnen valideren..

**Comment by sergejvm** [comment]
Wij gaan wel in gesprek met Medmij en VZVZ om te zien hoe we dit straks ook integraal kunnen testen, maar dat is iets voor na deze fase om rekening mee te houden.
