### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [GidsOpenStandaarden/OpenPGO#6]
Zouden jullie Travis "aan" kunnen zetten voor onze repositories zodat we automatisch kunnen laten testen als er een nieuwe commit wordt gedaan. Ook sonar check kan dan automatisch draaien.

**Comment by Hugo-ter-Doest** [comment]
Dit werkt nog niet. Ik krijg Travis niet te zien als app in de settings van mijn Nodejs repo. @othillo Is het jou gelukt om Travis toe te voegen aan jouw repo?

**Comment by Hugo-ter-Doest** [comment]
Blijkt toch wel te werken. Ik was te ongeduldig...

**Comment by othillo** [comment]
Het duurde langer dan ik dacht voordat Travis deze organisatie kon zien.
