### ISSUE TITLE
SonarCloud ondersteunt geen externe pull requests i.c.m. Travis CI

### ISSUE THREAD

**Issue by othillo** [GidsOpenStandaarden/OpenPGO#7]
SonarCloud ondersteunt geen externe pull requests i.c.m. Travis CI zoals beschreven op https://docs.travis-ci.com/user/sonarcloud/#upcoming-improvements.

Dit maakt SonarCloud onbruikbaar in een open-source workflow waarin leveranciers werken op een fork en pull requests sturen naar deze GitHub organisatie.

**Comment by Hugo-ter-Doest** [comment]
Ik heb dit ook geprobeerd en Travis start sonar start wel op, maar geeft volgende foutmelding:
```
ERROR: Project was never analyzed. A regular analysis is required before analyzing a pull request
```
Om dit werkend te krijgen moet de organisatie GidsOpenStandaarden onze projecten aanmelden bij Sonar. Daarvoor moet de projectKey zoals in de `sonar-project.properties` file gedefinieerd worden gebruikt. Bij mij is dat `GidsOpenStandaarden:OpenPGO-Medmij-ImplementatieBouwstenen-NodeJS`.

Zie ook mijn pull request https://github.com/GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-NodeJS/pull/1

En deze post op het forum van sonar:
https://community.sonarsource.com/t/project-was-never-analyzed-when-analysing-on-sonarcloud-with-travis/511

**Comment by Hugo-ter-Doest** [comment]
Ik heb het gefixed bij mijn eigen repo. En ik zag dat het bij de Python repo ook werkt. Ik heb gewoon mijn eigen organisatie naam hugo-ter-doest-github gebruikt en de project key node-medmij die ik eerder al had gebruikt voor het aanroepen van Sonar. Zie verder mijn `.travis.yaml` en `sonar-project.properties` files.

Volgende is nu het probleem met de coverage new code op te lossen.

**Comment by othillo** [comment]
Het probleem is dat SonarCloud met Travis CI niet werkt als je een pull request stuurt van een fork naar de originele repo.

see https://travis-ci.org/GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-NodeJS/jobs/435463175 en https://github.com/GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-NodeJS/pull/2/files

Dat is precies de workflow die bij open source gebruikt wordt.
