### ISSUE TITLE
404 for all example data links

### ISSUE THREAD

**Issue by Farmertjes** [GidsOpenStandaarden/OpenPGO#9]
### Preconditions (*)

NVT

### Steps to reproduce (*)

1. Visit Github page
2. Click example data link
3. 404

### Expected result (*)

1. Web page with example data

### Actual result (*)

1. 404

**Comment by sergejvm** [comment]
Hi @Farmertjes thanks for bringing this to our attention. This issue is caused by the phasing out of the website where the content was linked. We will try to resolve it asap.

**Comment by othillo** [comment]
Hoi Sergej,

Zeker goed, ik ga eind september nog op vakantie.
Dit heeft er inderdaad mee te maken dat die website uit is. Ik ga kijken of
ik die bestanden nog heb en ik zal ze dan in deze repo zetten.

groet,

Sander

**Comment by othillo** [comment]
Hi, @Farmertjes I updated the links and pointed them to the 	
MedMij Afsprakenstelsel Publiek Confluence. Does that work for you?
